{% set version = '3.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-covr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/covr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/covr/covr_{{ version }}.tar.gz
  sha256: ea90daa48011e4ac4431ae47ee02fad98f54b529fc3900281cbeef7a2edef0a0

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2

test:
  commands:
    - $R -e "library('covr')"           # [not win]
    - "\"%R%\" -e \"library('covr')\""  # [win]

about:
  home: https://github.com/r-lib/covr
  license: GPL-3
  summary: Track and report code coverage for your package and (optionally) upload the results
    to a coverage service like 'Codecov' <http://codecov.io> or 'Coveralls' <http://coveralls.io>.
    Code coverage is a measure of the amount of code being exercised by a set of tests.
    It is an indirect measure of test quality and completeness. This package is compatible
    with any testing methodology or framework and tracks coverage of both R code and
    compiled C/C++/FORTRAN code.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast

# Encoding: UTF-8
# Package: covr
# Title: Test Coverage for Packages
# Version: 3.2.1
# Authors@R: c( person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre")), person("Willem", "Ligtenberg", role = "ctb"), person("Kirill", "Mller", role = "ctb"), person("Henrik", "Bengtsson", role = "ctb"), person("Steve", "Peak", role = "ctb"), person("Kirill", "Sevastyanenko", role = "ctb"), person("Jon", "Clayden", role = "ctb"), person("Robert", "Flight", role = "ctb"), person("Eric", "Brown", role = "ctb"), person("Brodie", "Gaslam", role = "ctb"), person("Will", "Beasley", role = "ctb"), person("Robert", "Krzyzanowski", role = "ctb"), person("Markus", "Wamser", role = "ctb"), person("Karl", "Forner", role = "ctb"), person("Gergely", "Darczi", role = "ctb"), person("Jouni", "Helske", role = "ctb"), person("Kun", "Ren", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Ken", "Williams", role = "ctb"), person("Chris", "Campbell", role = "ctb"), person("David", "Hugh-Jones", role = "ctb"), person("Qin", "Wang", role = "ctb"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library"), person("Mark", "Otto", role = "ctb", comment = "Bootstrap library"), person("Jacob", "Thornton", role = "ctb", comment = "Bootstrap library"), person(family = "Bootstrap contributors", role = "ctb", comment = "Bootstrap library"), person(family = "Twitter, Inc", role = "cph", comment = "Bootstrap library") )
# Description: Track and report code coverage for your package and (optionally) upload the results to a coverage service like 'Codecov' <http://codecov.io> or 'Coveralls' <http://coveralls.io>. Code coverage is a measure of the amount of code being exercised by a set of tests. It is an indirect measure of test quality and completeness. This package is compatible with any testing methodology or framework and tracks coverage of both R code and compiled C/C++/FORTRAN code.
# URL: https://github.com/r-lib/covr
# BugReports: https://github.com/r-lib/covr/issues
# Depends: R (>= 3.1.0), methods
# Imports: digest, stats, utils, jsonlite, rex, httr, crayon, withr (>= 1.0.2)
# Suggests: R6, knitr, rmarkdown, htmltools, DT (>= 0.2), testthat, rstudioapi (>= 0.2), xml2 (>= 1.0.0), parallel, memoise, mockery
# License: GPL-3
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-10-18 15:49:20 UTC; jhester
# Author: Jim Hester [aut, cre], Willem Ligtenberg [ctb], Kirill Mller [ctb], Henrik Bengtsson [ctb], Steve Peak [ctb], Kirill Sevastyanenko [ctb], Jon Clayden [ctb], Robert Flight [ctb], Eric Brown [ctb], Brodie Gaslam [ctb], Will Beasley [ctb], Robert Krzyzanowski [ctb], Markus Wamser [ctb], Karl Forner [ctb], Gergely Darczi [ctb], Jouni Helske [ctb], Kun Ren [ctb], Jeroen Ooms [ctb], Ken Williams [ctb], Chris Campbell [ctb], David Hugh-Jones [ctb], Qin Wang [ctb], Ivan Sagalaev [ctb, cph] (highlight.js library), Mark Otto [ctb] (Bootstrap library), Jacob Thornton [ctb] (Bootstrap library), Bootstrap contributors [ctb] (Bootstrap library), Twitter, Inc [cph] (Bootstrap library)
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-10-18 16:40:03 UTC
