{% set version = "3.6.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-covr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/covr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/covr/covr_{{ version }}.tar.gz
  sha256: 2b6204036510c629d0b1d58daaee34d4e38baf54164f8d4c9afd6d6b1fb1862a

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rex                      # [build_platform != target_platform]
    - r-digest                   # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - r-crayon                   # [build_platform != target_platform]
    - r-httr                     # [build_platform != target_platform]
    - r-yaml                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2
    - r-yaml
  run:
    - r-base
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2
    - r-yaml

test:
  commands:
    - $R -e "library('covr')"           # [not win]
    - "\"%R%\" -e \"library('covr')\""  # [win]

about:
  home: https://github.com/r-lib/covr
  license: GPL-3.0-only
  summary: Track and report code coverage for your package and (optionally) upload the results to a coverage service like 'Codecov' <http://codecov.io> or 'Coveralls' <http://coveralls.io>. Code coverage is a measure of the amount of code being exercised by a set of tests. It is an indirect measure of test quality and completeness.
    This package is compatible with any testing methodology or framework and tracks coverage of both R code and compiled C/C++/FORTRAN code.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Encoding: UTF-8
# Package: covr
# Title: Test Coverage for Packages
# Version: 3.3.1
# Authors@R: c( person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre")), person("Willem", "Ligtenberg", role = "ctb"), person("Kirill", "Mller", role = "ctb"), person("Henrik", "Bengtsson", role = "ctb"), person("Steve", "Peak", role = "ctb"), person("Kirill", "Sevastyanenko", role = "ctb"), person("Jon", "Clayden", role = "ctb"), person("Robert", "Flight", role = "ctb"), person("Eric", "Brown", role = "ctb"), person("Brodie", "Gaslam", role = "ctb"), person("Will", "Beasley", role = "ctb"), person("Robert", "Krzyzanowski", role = "ctb"), person("Markus", "Wamser", role = "ctb"), person("Karl", "Forner", role = "ctb"), person("Gergely", "Darczi", role = "ctb"), person("Jouni", "Helske", role = "ctb"), person("Kun", "Ren", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Ken", "Williams", role = "ctb"), person("Chris", "Campbell", role = "ctb"), person("David", "Hugh-Jones", role = "ctb"), person("Qin", "Wang", role = "ctb"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library"), person("Mark", "Otto", role = "ctb", comment = "Bootstrap library"), person("Jacob", "Thornton", role = "ctb", comment = "Bootstrap library"), person(family = "Bootstrap contributors", role = "ctb", comment = "Bootstrap library"), person(family = "Twitter, Inc", role = "cph", comment = "Bootstrap library") )
# Description: Track and report code coverage for your package and (optionally) upload the results to a coverage service like 'Codecov' <http://codecov.io> or 'Coveralls' <http://coveralls.io>. Code coverage is a measure of the amount of code being exercised by a set of tests. It is an indirect measure of test quality and completeness. This package is compatible with any testing methodology or framework and tracks coverage of both R code and compiled C/C++/FORTRAN code.
# URL: https://github.com/r-lib/covr
# BugReports: https://github.com/r-lib/covr/issues
# Depends: R (>= 3.1.0), methods
# Imports: digest, stats, utils, jsonlite, rex, httr, crayon, withr (>= 1.0.2), yaml
# Suggests: R6, knitr, rmarkdown, htmltools, DT (>= 0.2), testthat, rlang, rstudioapi (>= 0.2), xml2 (>= 1.0.0), parallel, memoise, mockery
# License: GPL-3
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-08-23 19:38:31 UTC; Administrator
# Author: Jim Hester [aut, cre], Willem Ligtenberg [ctb], Kirill Mller [ctb], Henrik Bengtsson [ctb], Steve Peak [ctb], Kirill Sevastyanenko [ctb], Jon Clayden [ctb], Robert Flight [ctb], Eric Brown [ctb], Brodie Gaslam [ctb], Will Beasley [ctb], Robert Krzyzanowski [ctb], Markus Wamser [ctb], Karl Forner [ctb], Gergely Darczi [ctb], Jouni Helske [ctb], Kun Ren [ctb], Jeroen Ooms [ctb], Ken Williams [ctb], Chris Campbell [ctb], David Hugh-Jones [ctb], Qin Wang [ctb], Ivan Sagalaev [ctb, cph] (highlight.js library), Mark Otto [ctb] (Bootstrap library), Jacob Thornton [ctb] (Bootstrap library), Bootstrap contributors [ctb] (Bootstrap library), Twitter, Inc [cph] (Bootstrap library)
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-08-23 21:20:02 UTC
