{% set version = "3.0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-covr
  version: {{ version|replace("-", "_") }}

source:
  fn: covr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/covr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/covr/covr_{{ version }}.tar.gz
  sha256: 66b799fd03cb83a9ab382d9cf4ff40603d1e3f3a89905a3174546b0c63e8d184

build:
  merge_build_host: True  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2

  run:
    - r-base
    - r-crayon
    - r-digest
    - r-httr
    - r-jsonlite
    - r-rex
    - r-withr >=1.0.2

test:
  commands:
    - $R -e "library('covr')"           # [not win]
    - "\"%R%\" -e \"library('covr')\""  # [win]

about:
  home: https://github.com/r-lib/covr
  license: GPL-3
  summary: Track and report code coverage for your package and (optionally) upload the results
    to a coverage service like 'Codecov' <http://codecov.io> or 'Coveralls' <http://coveralls.io>.
    Code coverage is a measure of the amount of code being exercised by a set of tests.
    It is an indirect measure of test quality and completeness. This package is compatible
    with any testing methodology or framework and tracks coverage of both R code and
    compiled C/C++/FORTRAN code.
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - jdblischak
    - johanneskoester
    - bgruening
