travis:
  secure:
    BINSTAR_TOKEN: Ygh4CxgEfmv8k0lQT90dI6MrFDO1QMYwjwVfv8gKyZfPnZTDTnxxA53yJSfpjs906DSrV6sX1/wUQAJz7KscT5YAnxzjH6LxzBle1VaQ0TRqiNN1jWaFueI/oSy502F/Wbjro1pbjJbP2arNYr3eDypw3dnNy648t0eRA5XyEnLqGZi9kTPQ+bVqmIbGjLm9EG6MBZb+qQLgObh4uQaX12utF2kWTU5rfG1cSsWZBy1Qokyg4XEFF203ze5LFqO1NsKMD8vGkhD89pqVRZP77LTncLvptx1WvnIBl7xNEVMEYZpHVpEMEFFgZExXuvEvKAYlWgwRhsqYY9PXTaZY237p3ABtOApHRmj1um9wi/b9QtrUqOCaZ6BeK1sxYOq40mCGLs3V0DNXmDr8Z9fMNJXgWIyPvjzJYtinW0R/aTtX+8B+MZY/VpJvINU8j9xwM5GOHmJZY9mJU6IBFRnOq5TDP5wjVJB+a50yqgiBbHFzKuR55Okv/xShFjhfNconX7BWElUj3OyOR6Y2/5BigUgadV8ASx5hx0Eb2MM+z7NJB6yHsK7a7BvaTsm3gkePyiSbFyZy5Kkh8PL6pUex9guJtlXlleZtmAQpbmR26Ak6GJYkOq6OdkQAgD0N/2q3FfR+9zio7Cyj3RjoLldpyVu5p9gKjoOVi8paOvTMuvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
