appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RZxpETx8Lv5Q7Fbq6s4FKjuaKjF70wkeUxdiuQa3Pc4ZF/OGQG/Nq9TQO6MykkSDNsRQCRcsRvL1q63bdhKk155brYeLKWQtJarcdzCHXQtd3eWQm3H609A0ceKxwSBooWznKR8LMKzLG5ebkbnBHZngnSP1i5Z8TtSZ/yw21+p5uBCJ0Kv6fgWrotz1nUIHdaKp4SLbowf8vzWN9dpQlz2tln9odx3eGVKX8HQ8S6v9quaEVKiCryU9NILFf/tCbDhHX48sf9u7J8dhdrPa3j/HDtSKG/OJUrxEyJSrRJ9CISEYnqbPqALpjeTmhfCCUBABGy93L8NcKDrOsKTEt4WyGseO9BMkQLwvjBG2P1d/dLu72TjBWDGX1K4dtTvqoe+yE5dlr5FTVOXfq1urYN04bTyKAgyQeVZ4EnBgy38xZtkZrmiA21ZSew+FjXgm5T5XNLLIpz0yG0yNnJydVkoaauxn6y7Fajex7u0z9mjqW8SpNgb2VWmtMpdXxgPxyR8HzsmEtynGPX5vdZa/r3BWLggJ54z/xfzfa2h1JJQKW7IPuMv6tqxa68hVGhrFFmuxKcYPKqVgd7U4VrgjWY/QvDJ+qHVUHDVb+bsyO6Tr0XCrGeLYte+sAYxw+BAY9OvkPAaxJX7uqvtIvj+grRh9EpYu+qRSPOvquViwD1Q=}
bot:
  automerge: true
