travis:
  secure:
    BINSTAR_TOKEN: p+yx7bkVYEo9ibNDMNptayrfI3YttFu7CGBySqZN73kPgQV1LQvNvxckVa3btZPB5OvH7Z6Lu2F3xjEtz8gNx7uT2ldOULmBB5ZvBbvX+pixQ+ltVjj8743nYFLlznm/y0y7kaFP5ZKyVWk12EEMLcu0e9DJ2a0CjwV2cdRSs+uiwbmr3KLVtt7ZrMdxxxbtjdLl5CbDIb8X8m7V2BikIAveo2ahndM8LObkOicu1GEd47jXo+3ycsFvc81HL8nukp97e6QB7GBIHvr8icBVjCk+5oq7zLYn02swY59d7ZPNt8eMvfP98v0cgLJj/NnUdQo5fo0MTmypCflVAH4M5MzT2372D995N87HNAMfxyjwVSznTFiLQpBUaiay7wN7HyaElJULrk/Nn2tFU8oemPqGNY8nsX8k8sqDrJk2APcTWV4hD4aBcf+tPuap69g9bimbzxLYK1lfh1E7CWboDfTEoQ0ZVk/WUqMxY5p24s1igYlUsiyzsmAM6cEX/eEvaXESgcYmqkbsCLKfFdxBcvOaPl/zqrcI63u0PaJxTJgmKAuR7eLUaaWNBJEQ589ekohDdqkvNgb9mkQhSQSYo6wLKhCxewz0n14ldAEVjTmjL5iGWTn4AaMDwbsFFCCKPCM0cTfN7swG5c7/u1NgKr9E+YOZzEKFuP0xIpK37CE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
